linters-settings:
  golint:
    min-confidence: 0

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - deadcode
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - structcheck
    - typecheck

issues:
  exclude-use-default: false
  exclude:
      - should have a package comment
      - error strings should not be capitalized or end with punctuation or a newline
